services:
  app:
    build:
      context: .
      target: production-main
      dockerfile: Dockerfile
    ports:
      - "5905-5906:3000"
    env_file:
      - website/.env
    depends_on:
      - websocket
    restart: unless-stopped
    networks:
      - shared_backend
    volumes:
      - uploads:/app/uploads
    deploy:
      replicas: 2

  websocket:
    build:
      context: .
      target: production-websocket
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - website/.env
    restart: unless-stopped
    networks:
      - shared_backend

networks:
  shared_backend:
    external: true

volumes:
  uploads: